name: tires_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.2.0
  auto_route: ^3.2.4
  provider: ^6.0.3
  http: ^0.13.4
  persistent_bottom_nav_bar: ^4.0.2
  rflutter_alert: ^2.0.4
  sliding_up_panel: ^2.0.0+1
  connectivity_plus: ^2.3.5
  intl: ^0.17.0
  syncfusion_flutter_datagrid: ^20.1.61
  # workmanager: ^0.5.0
  flutter_launcher_icons: ^0.11.0
  path_provider: ^2.0.11
  open_file_safe: ^3.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  holding_gesture: ^1.1.0
  socket_io_client: ^2.0.0
  web_socket_channel: ^2.2.0
  flutter_background_service: ^2.4.5
  shared_preferences: ^2.0.15
  device_info_plus: ^4.0.0
  flutter_local_notifications: ^12.0.2
  sqflite: ^2.0.3+1
  flutter_rating_bar: ^4.0.1
  device_information: ^0.0.4
  permission_handler: ^10.2.0
  flutter_dotenv: ^5.0.2
  ftoast: ^2.0.0
  fluttertoast: ^8.1.2
  firebase_core: any
  firebase_messaging: ^14.2.0
  firebase_core_web: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^3.2.3
  freezed: ^1.1.1
  freezed_annotation: ^1.1.0
  hive_generator: ^1.1.3
  build_runner: ^2.1.11


flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/shlogo.png"


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/Siyob Agromash-3.png
    - lib/.env